const FRAME_SIZE = 'FRAME_SIZE';
const BIKE_TYPE = 'BIKE_TYPE';

const REQUEST_FRAME_JSON = 'REQUEST_FRAME_JSON';
const RECEIVE_FRAME_JSON = 'RECEIVE_FRAME_JSON';

export default {
    FRAME_SIZE,
    BIKE_TYPE,
    REQUEST_FRAME_JSON,
    RECEIVE_FRAME_JSON
}