const FRAME_SIZE = 'FRAME_SIZE';
const BIKE_TYPE = 'BIKE_TYPE';

const REQUEST_FRAME_JSON = 'REQUEST_FRAME_JSON';
const RECEIVE_FRAME_JSON = 'RECEIVE_FRAME_JSON';
const SHOW_FRAME_COMPONENT = 'SHOW_FRAME_COMPONENT';
const SHOW_FRAME_SIZE_COMPONENT = 'SHOW_FRAME_SIZE_COMPONENT';

export default {
    FRAME_SIZE,
    BIKE_TYPE,
    REQUEST_FRAME_JSON,
    RECEIVE_FRAME_JSON,
    SHOW_FRAME_COMPONENT,
    SHOW_FRAME_SIZE_COMPONENT
}