const FRAME_SIZE = 'FRAME_SIZE';
const BIKE_TYPE = 'BIKE_TYPE';
const WHEELS_SIZE = 'WHEELS_SIZE';

const REQUEST_FRAME_JSON = 'REQUEST_FRAME_JSON';
const RECEIVE_FRAME_JSON = 'RECEIVE_FRAME_JSON';
const SHOW_FRAME_COMPONENT = 'SHOW_FRAME_COMPONENT';
const SHOW_FRAME_SIZE_COMPONENT = 'SHOW_FRAME_SIZE_COMPONENT';
const SHOW_WHEELS_SIZE_COMPONENT = 'SHOW_WHEELS_SIZE_COMPONENT';
const REQUEST_MANUFACTURER_JSON = 'REQUEST_MANUFACTURER_JSON';
const RECEIVE_MANUFACTURER_JSON = 'RECEIVE_MANUFACTURER_JSON';
const REQUEST_FORK_JSON = 'REQUEST_FORK_JSON';
const RECEIVE_FORK_JSON = 'RECEIVE_FORK_JSON';
const SHOW_FORK_COMPONENT = 'SHOW_FORK_COMPONENT';
export default {
    FRAME_SIZE,
    BIKE_TYPE,
    WHEELS_SIZE,
    REQUEST_FRAME_JSON,
    RECEIVE_FRAME_JSON,
    SHOW_FRAME_COMPONENT,
    SHOW_FRAME_SIZE_COMPONENT,
    SHOW_WHEELS_SIZE_COMPONENT,
    REQUEST_MANUFACTURER_JSON,
    RECEIVE_MANUFACTURER_JSON,
    REQUEST_FORK_JSON,
    RECEIVE_FORK_JSON,
    SHOW_FORK_COMPONENT
}
